# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protob.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protob.proto", :syntax => :proto3) do
    add_message "protob.Version" do
      optional :value, :string, 1
    end
    add_message "protob.Void" do
    end
    add_message "protob.Title" do
      optional :id, :int32, 1
      optional :archive_id, :string, 2
      optional :path, :string, 3
      optional :lang, :string, 4
    end
    add_message "protob.TitlesOpt" do
    end
    add_message "protob.Page" do
      optional :id, :string, 1
      optional :offset, :int32, 2
      optional :text, :bytes, 3
      optional :title_id, :string, 4
      optional :title_path, :string, 5
      repeated :names, :message, 6, "protob.NameString"
    end
    add_message "protob.PagesOpt" do
      optional :with_text, :bool, 1
      optional :offsets_only, :bool, 2
      repeated :title_ids, :int32, 3
    end
    add_message "protob.NameString" do
      optional :id, :string, 1
      optional :value, :string, 2
      optional :taxon_id, :string, 3
      optional :matched, :string, 4
      optional :matched_canonical, :string, 5
      optional :current, :string, 6
      optional :odds, :float, 7
      optional :occurences, :int32, 8
      optional :classification, :string, 9
      optional :curated, :bool, 10
      optional :edit_distance, :int32, 11
      optional :edit_distance_stem, :int32, 12
      optional :data_source_id, :int32, 13
      optional :data_source_title, :string, 14
      optional :data_sources_num, :int32, 15
      optional :match, :enum, 16, "protob.MatchType"
      optional :offset_start, :int32, 17
      optional :offset_end, :int32, 18
      optional :verif_error, :bool, 19
      repeated :preferred, :message, 20, "protob.PreferredResult"
    end
    add_message "protob.PreferredResult" do
      optional :taxon_id, :string, 1
      optional :matched, :string, 2
      optional :matched_canonical, :string, 3
      optional :current, :string, 4
      optional :path, :string, 5
      optional :edit_distance, :int32, 7
      optional :edit_distance_stem, :int32, 8
      optional :data_source_id, :int32, 9
      optional :data_source_title, :string, 10
      optional :match, :enum, 11, "protob.MatchType"
    end
    add_message "protob.NamesOpt" do
      optional :with_preferred_results, :bool, 1
    end
    add_enum "protob.MatchType" do
      value :NONE, 0
      value :EXACT, 1
      value :CANONICAL_EXACT, 2
      value :CANONICAL_FUZZY, 3
      value :PARTIAL_EXACT, 4
      value :PARTIAL_FUZZY, 5
    end
  end
end

module Protob
  Version = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Version").msgclass
  Void = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Void").msgclass
  Title = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Title").msgclass
  TitlesOpt = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.TitlesOpt").msgclass
  Page = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Page").msgclass
  PagesOpt = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.PagesOpt").msgclass
  NameString = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.NameString").msgclass
  PreferredResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.PreferredResult").msgclass
  NamesOpt = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.NamesOpt").msgclass
  MatchType = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.MatchType").enummodule
end
